version: '2'

services:

  mssql:
    image: microsoft/mssql-server-linux:latest
    container_name: mssql
    hostname: mssqlcont
    restart: always
    networks:
      - mssql-tier
    ports:
      - 1433:1433
    expose:
      - 1433
    volumes:
      - mssql-db:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P4ssw0rd+
      - MSSQL_PID=Developer

volumes:
  mssql-db:
    external: true

networks:
  mssql-tier:
    driver: bridge
